/**
 * Lược đồ cơ sở dữ liệu, dạng migration đánh số.
 *
 * QUY TẮC: đã chạy trên môi trường thật thì **không sửa** mục cũ — thêm mục mới.
 * Mỗi mục phải idempotent (dùng IF NOT EXISTS) để chạy lại không gây lỗi.
 *
 * Mục 1–5 được viết lại cho PostgreSQL ngày 17/09/2026. Bản SQLite cũ chưa từng
 * chạy trên môi trường thật với dữ liệu cần giữ (container bị xoá mỗi lần triển
 * khai lại), nên đổi tại chỗ thay vì thêm mục 6 để dịch lược đồ.
 *
 * Quy ước kiểu dữ liệu, khác bản SQLite cũ:
 *   - khoá chính tự tăng  → `GENERATED BY DEFAULT AS IDENTITY`
 *   - cột thời gian       → `TIMESTAMPTZ DEFAULT now()`, đọc ra thành chuỗi
 *                           `YYYY-MM-DD HH:MM:SS` nhờ bộ chuyển kiểu ở `pool.js`
 *   - cột đúng/sai        → `BOOLEAN`, không còn `INTEGER 0/1`
 *   - email không phân biệt hoa thường → index duy nhất trên `lower(email)`
 */
export const MIGRATIONS = [
  {
    id: 1,
    name: 'core — khách tiềm năng, chẩn đoán, sự kiện, hàng đợi thư',
    sql: `
      CREATE TABLE IF NOT EXISTS leads (
        id          INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        name        TEXT        NOT NULL,
        phone       TEXT        NOT NULL,
        email       TEXT        NOT NULL,
        company     TEXT,
        industry    TEXT,
        service     TEXT,
        message     TEXT,
        source      TEXT,
        page        TEXT,
        referrer    TEXT,
        utm         TEXT,
        score       INTEGER,
        tier        TEXT,
        diagnostic  TEXT,
        status      TEXT        NOT NULL DEFAULT 'new',
        ip_hash     TEXT,
        user_agent  TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_leads_created ON leads(created_at DESC);
      CREATE INDEX IF NOT EXISTS idx_leads_status  ON leads(status);
      CREATE INDEX IF NOT EXISTS idx_leads_source  ON leads(source);

      CREATE TABLE IF NOT EXISTS diagnostics (
        id          INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        industry    TEXT,
        revenue     BIGINT,
        overall     INTEGER     NOT NULL,
        tier        TEXT,
        layers      TEXT        NOT NULL,
        answers     TEXT        NOT NULL,
        leak_month  BIGINT,
        ip_hash     TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_diag_created ON diagnostics(created_at DESC);

      CREATE TABLE IF NOT EXISTS events (
        id          INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        kind        TEXT        NOT NULL,
        detail      TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_events_created ON events(created_at DESC);

      CREATE TABLE IF NOT EXISTS outbox (
        id           INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
        kind         TEXT        NOT NULL,
        recipient    TEXT        NOT NULL,
        subject      TEXT        NOT NULL,
        html         TEXT        NOT NULL,
        text         TEXT        NOT NULL,
        reply_to     TEXT,
        lead_id      INTEGER,
        status       TEXT        NOT NULL DEFAULT 'pending',
        attempts     INTEGER     NOT NULL DEFAULT 0,
        next_try_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_error   TEXT,
        sent_at      TIMESTAMPTZ
      );
      CREATE INDEX IF NOT EXISTS idx_outbox_due ON outbox(status, next_try_at);
    `
  },

  {
    id: 2,
    name: 'danh tính — tài khoản, phiên đăng nhập, nhật ký kiểm toán',
    sql: `
      CREATE TABLE IF NOT EXISTS users (
        id             INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
        email          TEXT        NOT NULL,
        name           TEXT        NOT NULL,
        password_hash  TEXT        NOT NULL,
        role           TEXT        NOT NULL DEFAULT 'viewer',
        active         BOOLEAN     NOT NULL DEFAULT TRUE,
        must_change_pw BOOLEAN     NOT NULL DEFAULT FALSE,
        last_login_at  TIMESTAMPTZ,
        failed_count   INTEGER     NOT NULL DEFAULT 0,
        locked_until   TIMESTAMPTZ
      );
      -- Email không phân biệt hoa thường: Postgres không có COLLATE NOCASE nên
      -- ràng buộc duy nhất đặt trên biểu thức. Mọi truy vấn tra email phải dùng
      -- lower(email) = lower($1) để index này được dùng tới.
      CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(lower(email));

      CREATE TABLE IF NOT EXISTS sessions (
        id          TEXT        PRIMARY KEY,   -- SHA-256 của mã phiên, không lưu mã gốc
        user_id     INTEGER     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_seen   TIMESTAMPTZ NOT NULL DEFAULT now(),
        expires_at  TIMESTAMPTZ NOT NULL,
        csrf_token  TEXT        NOT NULL,
        ip_hash     TEXT,
        user_agent  TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_sessions_user    ON sessions(user_id);
      CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

      CREATE TABLE IF NOT EXISTS audit_log (
        id          INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        actor_id    INTEGER,
        actor_email TEXT,
        action      TEXT        NOT NULL,
        target      TEXT,
        detail      TEXT,
        ip_hash     TEXT,
        result      TEXT        NOT NULL DEFAULT 'ok'
      );
      CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at DESC);
      CREATE INDEX IF NOT EXISTS idx_audit_actor   ON audit_log(actor_id);
      CREATE INDEX IF NOT EXISTS idx_audit_action  ON audit_log(action);
    `
  },

  {
    id: 3,
    name: 'vận hành bán hàng — ghi chú và người phụ trách khách tiềm năng',
    sql: `
      ALTER TABLE leads ADD COLUMN IF NOT EXISTS assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL;
      ALTER TABLE leads ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMPTZ;
      ALTER TABLE leads ADD COLUMN IF NOT EXISTS value_vnd   BIGINT;

      CREATE TABLE IF NOT EXISTS lead_notes (
        id          INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        lead_id     INTEGER     NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
        author_id   INTEGER     REFERENCES users(id) ON DELETE SET NULL,
        author_name TEXT,
        body        TEXT        NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_notes_lead ON lead_notes(lead_id, created_at DESC);
    `
  },

  {
    id: 4,
    name: 'nội dung động — tham số site sửa được từ bảng điều khiển',
    sql: `
      CREATE TABLE IF NOT EXISTS settings (
        key         TEXT        PRIMARY KEY,
        value       TEXT        NOT NULL,
        updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_by  INTEGER     REFERENCES users(id) ON DELETE SET NULL
      );
    `
  },

  {
    id: 5,
    name: 'nội dung — lớp phủ cho phép sửa/thêm/xoá mọi mục từ bảng điều khiển',
    sql: `
      -- Lớp phủ nội dung.
      --
      -- Dữ liệu gốc vẫn nằm trong site/data/*.js và vẫn là bản chuẩn đi kèm mã
      -- nguồn. Bảng này chỉ ghi phần KHÁC BIỆT do người dùng tạo ra: sửa một
      -- mục, thêm mục mới, hoặc ẩn một mục có sẵn.
      --
      -- Chọn cách này thay vì nhồi toàn bộ nội dung vào cơ sở dữ liệu vì hai lẽ:
      -- website vẫn khởi động được và vẫn đầy đủ khi tệp dữ liệu trống rỗng, và
      -- mọi thay đổi đều hoàn tác được bằng một nút bấm — xoá dòng phủ là nội
      -- dung gốc trở lại y nguyên.
      CREATE TABLE IF NOT EXISTS content (
        id          INTEGER     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        collection  TEXT        NOT NULL,
        item_id     TEXT        NOT NULL,
        data        TEXT,                            -- JSON; NULL khi chỉ đánh dấu xoá
        origin      TEXT        NOT NULL DEFAULT 'override',  -- override | new
        deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
        position    INTEGER,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_by  INTEGER     REFERENCES users(id) ON DELETE SET NULL
      );
      CREATE UNIQUE INDEX IF NOT EXISTS idx_content_item ON content(collection, item_id);
      CREATE INDEX IF NOT EXISTS idx_content_collection ON content(collection);
    `
  }
];

export default MIGRATIONS;
